# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7ee11f00a83cc7c6572b4cb134c0a730fb91bf290bb429b4fa6785385103f4235c602d7022754256ecf63898ab731995cbae963a0448e76b8e791318293ae91

test:
  secret_key_base: 314b2bf0db91879c6ccd895330f0b5ed9c9fdb7d78936fa1d28f24035389c56ab584623b079e255414d0bc53f0f5b558ffe823294b7f881cb8c7e79624c9907d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
